# ================================
# BASE PROGUARD GENERATED BY ANDROID STUDIO
# ================================

# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Uncomment this to preserve the line number information for
# debugging stack traces.
-keepattributes SourceFile,LineNumberTable

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# ================================
# TENSORFLOW LITE PROGUARD RULES
# ================================

-keep class org.tensorflow.lite.** { *; }
-keep class org.tensorflow.lite.support.** { *; }
-keepclasseswithmembernames class * {
    native <methods>;
}
-keep class * extends org.tensorflow.lite.support.model.Model { *; }

# Keep custom detector classes
-keep class com.example.irislens.money.model.MoneyDetector { *; }
-keep class com.example.irislens.money.model.MoneyDetector$* { *; }

# ================================
# OPENCV PROGUARD RULES
# ================================

-keep class org.opencv.** { *; }
-keep class org.opencv.android.** { *; }

# ================================
# TESSERACT PROGUARD RULES
# ================================

-keep class cz.adaptech.tesseract4android.** { *; }

# ================================
# FIREBASE PROGUARD RULES
# ================================

-keep class com.google.firebase.** { *; }
-keep class com.google.android.gms.** { *; }

# ================================
# GENERAL ANDROID RULES
# ================================

# Keep custom activities and views
-keep class com.example.irislens.** { *; }

# Keep Parcelable implementations
-keep class * implements android.os.Parcelable {
    public static final android.os.Parcelable$Creator *;
}

# Keep serializable classes
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    !static !transient <fields>;
    !private <fields>;
    !private <methods>;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}

# ================================
# REFLECTION RULES
# ================================

-keepattributes *Annotation*
-keepattributes Signature
-keepattributes InnerClasses
-keepattributes EnclosingMethod